#!/usr/bin/env bash
# Install every skill from the single canonical source (~/claude/paper-tools)
# into the three harnesses on ganymede:
#
#   Claude Code : ~/.claude/skills/<name>/      (symlinks -> canonical)
#   DSH  (DeepSeek Harness web GUI) : ~/.dsh/skills/<name>/SKILL.md  (generated)
#   Kimi Code   : ~/.kimi-code/skills/<name>/SKILL.md  (generated)
#
# Re-run this after any `git pull` of paper-tools to refresh every harness.
# Idempotent: safe to run repeatedly.
set -euo pipefail

PAPER="$HOME/claude/paper-tools"
VENV="$PAPER/.venv/bin/python"

# name:canonical-dir  (canonical dir must contain SKILL.md)
SKILLS="
check-citations:check-citations
validation:validation
"

quote_yaml() { python3 -c 'import sys,json; print(json.dumps(sys.stdin.read().rstrip("\n")))'; }

# Generate a self-contained SKILL.md for harnesses that want a flat file rather
# than a symlink. Kimi's YAML parser is strict: an unquoted plain scalar
# containing ": " is a parse error and silently drops the whole skill, so the
# description is always emitted double-quoted (JSON-escaped). DSH wants
# name/description/whenToUse; Kimi additionally wants `type: prompt`.
generate_copy() { # $1=src SKILL.md  $2=dest  $3=name  $4=add-type(0/1)
  local src="$1" dest="$2" name="$3" addtype="$4"
  local desc when desc_q when_q
  desc=$(awk '/^description:/{sub(/^description: */,""); print; exit}' "$src")
  when=$(awk '/^whenToUse:/{sub(/^whenToUse: */,""); print; exit}' "$src")
  # If the canonical value is already double-quoted, strip exactly one layer so
  # quote_yaml below does not double-quote it (producing "\"...\"").
  strip_quotes() { local v="$1"; case "$v" in '"'*'"') v="${v#\"}"; v="${v%\"}";; esac; printf '%s' "$v"; }
  desc=$(strip_quotes "$desc")
  when=$(strip_quotes "$when")
  desc_q=$(printf '%s' "$desc" | quote_yaml)
  when_q=$(printf '%s' "$when"  | quote_yaml)
  {
    printf -- '---\n'
    printf 'name: %s\n' "$name"
    printf 'description: %s\n' "$desc_q"
    if [ "$addtype" = "1" ]; then printf 'type: prompt\n'; fi
    if [ -n "$when" ]; then printf 'whenToUse: %s\n' "$when_q"; fi
    printf -- '---\n\n'
    printf '<!-- GENERATED by install_skills.sh from %s -- do not edit here. -->\n\n' "$src"
    # Body of the canonical SKILL.md, minus its own YAML frontmatter block.
    awk 'NR==1 && /^---$/ {fm=1; next} fm && /^---$/ {fm=0; next} !fm' "$src"
  } > "$dest"
}

install_one() {
  local name="$1" dir="$2"
  local src="$PAPER/$dir/SKILL.md"
  if [ ! -f "$src" ]; then
    echo "SKIP $name: $src missing" >&2
    return 1
  fi

  # ── Claude Code ─────────────────────────────────────────────────────
  local cc="$HOME/.claude/skills/$name"
  mkdir -p "$cc"
  ln -sfn "$src" "$cc/SKILL.md"
  # check-citations ships its driver beside the skill; keep it linked too.
  [ -f "$PAPER/$dir/check_citations.py" ] && \
    ln -sfn "$PAPER/$dir/check_citations.py" "$cc/check_citations.py"
  echo "[claude-code] $cc"

  # ── DSH (DeepSeek Harness) ──────────────────────────────────────────
  local ds="$HOME/.dsh/skills/$name"
  mkdir -p "$ds"
  generate_copy "$src" "$ds/SKILL.md" "$name" 0
  echo "[dsh]         $ds"

  # ── Kimi Code ───────────────────────────────────────────────────────
  local kc="$HOME/.kimi-code/skills/$name"
  mkdir -p "$kc"
  generate_copy "$src" "$kc/SKILL.md" "$name" 1
  echo "[kimi]        $kc"
}

# Stale legacy flat file: validation used to be ~/.claude/skills/validation.md.
# It is now a directory bundle; drop the old flat file so Claude Code does not
# load both.
if [ -f "$HOME/.claude/skills/validation.md" ]; then
  rm -f "$HOME/.claude/skills/validation.md"
  echo "[cleanup]     removed stale ~/.claude/skills/validation.md"
fi

for entry in $SKILLS; do
  name="${entry%%:*}"
  dir="${entry#*:}"
  install_one "$name" "$dir"
done

echo
echo "interpreter: $VENV"
[ -x "$VENV" ] && "$VENV" -c 'import sys; print("python", sys.version.split()[0])'
echo "canonical: $PAPER  (git pull + this script = full refresh)"
